
option(VQ3_COMPATIBLE_QVM "Produce a qvm file compatible with Q3 1.32b" ${DEFAULT_VQ3_COMPATIBLE_QVM})

if(VQ3_COMPATIBLE_QVM)
	set(VQ3_OPTION "-vq3")
else()
	set(VQ3_OPTION)
endif(VQ3_COMPATIBLE_QVM)


set(Q3CPP_VERBOSE_OPTION)
set(Q3LCC_VERBOSE_OPTION)

if(CMAKE_CONFIGURATION_TYPES)
	set(Q3CPP_VERBOSE_OPTION "$<$<CONFIG:Debug>:-v>")
	set(Q3LCC_VERBOSE_OPTION "$<$<CONFIG:Debug>:-v>")
endif(CMAKE_CONFIGURATION_TYPES)

if(CMAKE_BUILD_TYPE MATCHES "Debug")
	set(Q3CPP_VERBOSE_OPTION "-v")
	set(Q3LCC_VERBOSE_OPTION "-v")
endif()


#set(Q3LCC_OPTIIONS "-S" "-B")
#set(Q3CPP_OPTIIONS "-M" "-+")
