
set(Q3CPP_SUBDIR "${CMAKELIST_DIR}/tools/q3cpp")
if(NOT EXISTS "${Q3CPP_SUBDIR}/CMakeLists.txt")
	message(WARNING "Could not find q3cpp in: ${Q3CPP_SUBDIR}")
endif()
if(NOT DEFINED Q3CPP_TARGET)
	set(Q3CPP_TARGET "q3cpp")
endif()
if(NOT TARGET "${Q3CPP_TARGET}")
	add_subdirectory("${Q3CPP_SUBDIR}" "${CMAKE_CURRENT_BINARY_DIR}/q3cpp")
endif()

set(Q3ASM_SUBDIR "${CMAKELIST_DIR}/tools/q3asm")
if(NOT EXISTS "${Q3ASM_SUBDIR}/CMakeLists.txt")
	message(WARNING "Could not find q3asm in: ${Q3ASM_SUBDIR}")
endif()
if(NOT DEFINED Q3ASM_TARGET)
	set(Q3ASM_TARGET "q3asm")
endif()
if(NOT TARGET "${Q3ASM_TARGET}")
	add_subdirectory("${Q3ASM_SUBDIR}" "${CMAKE_CURRENT_BINARY_DIR}/q3asm")
endif()

set(Q3LCC_SUBDIR "${CMAKELIST_DIR}/tools/q3lcc")
if(NOT EXISTS "${Q3LCC_SUBDIR}/CMakeLists.txt")
	message(WARNING "Could not find q3lcc in: ${Q3LCC_SUBDIR}")
endif()
if(NOT DEFINED Q3LCC_TARGET)
	set(Q3LCC_TARGET "q3lcc")
endif()
if(NOT TARGET "${Q3LCC_TARGET}")
	add_subdirectory("${Q3LCC_SUBDIR}" "${CMAKE_CURRENT_BINARY_DIR}/q3lcc")
endif()

set(Q3RCC_SUBDIR "${CMAKELIST_DIR}/tools/q3rcc")
if(NOT EXISTS "${Q3RCC_SUBDIR}/CMakeLists.txt")
	message(WARNING "Could not find q3rcc in: ${Q3RCC_SUBDIR}")
endif()
if(NOT DEFINED Q3RCC_TARGET)
	set(Q3RCC_TARGET "q3rcc")
endif()
if(NOT TARGET "${Q3RCC_TARGET}")
	add_subdirectory("${Q3RCC_SUBDIR}" "${CMAKE_CURRENT_BINARY_DIR}/q3rcc")
endif()
